use std::time::SystemTime;

const RANDOM_TEXTS: [&str; 100] = [
    "A gentle breeze carried the colorful leaves across the quiet street.",
    "Small daily improvements often lead to remarkable results over time.",
    "The recipe called for fresh herbs, warm bread, and a little patience.",
    "She sorted the coins into small stacks and placed them in a tin box.",
    "The boat waited at the dock while gulls circled above the gray water.",
    "A neighbor brought over a basket of apples from the tree in the yard.",
    "A thin fog rolled across the field as the first birds began to sing.",
    "The radio played softly while someone hummed along in the next room.",
    "Fresh coffee filled the room while everyone prepared for the meeting.",
    "The recipe required 2 cups of flour, 1/2 teaspoon of salt, and 3 eggs.",
    "Learning to type accurately is more valuable than typing at high speed.",
    "A paper airplane drifted across the room and landed near the bookshelf.",
    "The clock above the door ticked steadily while rain tapped on the roof.",
    "Every successful project begins with a clear plan and consistent effort.",
    "He paid $14.20 for the ticket, kept the receipt, and boarded at gate 7B.",
    "The curious student solved the challenging puzzle with careful thinking.",
    "He folded the map carefully, tucked it into his pocket, and kept walking.",
    "The baker dusted flour from his hands and placed the tray near the window.",
    "Swift foxes jump over lazy dogs in a classic display of agility and speed.",
    "The classroom smelled of chalk and wood polish, and the windows were open.",
    "The trail markers were faded, so the group stopped often to compare routes.",
    "Bright stars covered the night sky as the travelers continued their journey.",
    "Practice with patience, stay focused, and celebrate every small achievement.",
    "Technology evolves rapidly, but strong fundamentals remain equally important.",
    "Before leaving, he checked the weather, grabbed an umbrella, and waved goodbye.",
    "The museum opened early for school groups, and the hallway filled with quiet whispers.",
    "The ferry crossed the bay slowly while seagulls trailed behind it against the pale sky.",
    "The greenhouse held warm air, damp soil, and rows of seedlings reaching toward the glass.",
    "A sudden bolt of lightning illuminated the valley, followed by a deafening crash of thunder.",
    "The cat leaped onto the fence, balancing perfectly before vanishing into the shadows of the night.",
    "The garden gate creaked when she pushed it open. Stone steps led to a small porch where a gray cat slept in a patch of sun.",
    "After the meeting ended, he walked back to his desk and reviewed the notes. A few questions remained, but the main plan was clear.",
    "The harbor reflected the evening sky in soft shades of orange and pink. Boats rocked gently while ropes tapped against wooden posts.",
    "Late afternoon light crossed the desk in thin golden stripes. Papers waited in neat piles, and the pen lay ready beside an open notebook.",
    "The campers woke early to find frost on the tent, and the fire pit needed coaxing before it produced enough warmth for a simple breakfast.",
    "The mountain trail narrowed as it climbed through pine trees. Hikers paused to drink water, check the map, and admire the wide view below.",
    "A narrow alley led to a courtyard full of potted plants. Someone had placed a small fountain near the wall, and water sparkled in the shade.",
    "Each morning, the baker arranged fresh loaves on the wooden shelf. The smell of warm bread drifted into the street and drew customers inside.",
    "A quiet train carried passengers through fields, tunnels, and sleeping towns. Some read novels, some watched the sky, and some simply rested.",
    "The market was busy with people moving between colorful stalls. Vendors called out prices while children pointed at sweets and bright balloons.",
    "The library was silent except for the faint sound of turning pages. A student sat near the window, taking careful notes from a thick blue book.",
    "The classroom projector hummed as slides changed one by one. Students copied the final diagram, and the teacher waited patiently for questions.",
    "The evening practice ended with a slow walk home. The air was cool, the streetlights were bright, and the sound of the game still echoed nearby.",
    "Snow began to fall quietly over the village, covering roofs and fences. Windows glowed with warm light, and footsteps left fresh marks along the road.",
    "The engineer reviewed the drawings one more time, noticed a small gap near the hinge, and marked it for correction before the model was sent to the workshop.",
    "The archive room smelled of paper and dust, and every shelf seemed to hold a different year, with labels written in careful ink that faded toward the edges.",
    "The painter mixed blue and gray on the palette, studying the way clouds gathered above the rooftops before beginning the first broad stroke across the empty canvas.",
    "Every evening, the keeper walked along the pier, checked the ropes, listened to the water, and made sure the little boats were safe before returning to the lamp room.",
    "After the concert ended, the crowd spilled into the cool street, still humming melodies while the band packed instruments and exchanged tired smiles behind the stage.",
    "When the power went out, the family lit candles, played card games by the kitchen table, and listened to the rain until the lights returned with a sudden cheerful blink.",
    "The old house stood at the end of the lane, its porch light flickering as moths danced around the warm yellow glow and the night breeze carried the scent of cut grass.",
    "An old photograph slipped out of the book unexpectedly. It captured a moment no one remembered clearly anymore. Yet somehow, it still carried the weight of a shared past.",
    "Although the task looked small at first, it required careful measurements, repeated tests, and a willingness to change the plan whenever the results pointed in a new direction.",
    "The market square came alive before sunrise, when bakers carried out trays of warm bread, florists arranged bright buckets, and the first customers arrived with sleepy smiles.",
    "The science fair had tables covered with models, charts, and blinking circuits, while students explained their ideas proudly and visitors moved slowly from one project to the next.",
    "The journey through the canyon took longer than planned, because the path twisted around fallen stones, crossed a narrow bridge, and narrowed where the walls leaned close together.",
    "He stared at the blank page longer than he wanted to admit. Writing always felt harder before the first sentence appeared. Once it did, the rest followed more naturally than expected.",
    "A small cafe sat quietly at the corner of the street. Inside, conversations blended with the sound of grinding coffee beans. Time seemed slower there, as if the outside world had briefly paused.",
    "The road stretched endlessly ahead, surrounded by open fields. Driving felt meditative, with nothing but the hum of the engine and the changing sky. Miles passed unnoticed until the sun dipped low.",
    "The dog waited by the door, tail wagging at every sound. It had learned to recognize footsteps long before they reached the house. When the door finally opened, excitement filled the room instantly.",
    "Neon lights flickered above the diner, casting a purple glow over the wet pavement. Inside, the smell of burnt toast and cheap coffee created a nostalgic atmosphere for those seeking refuge from the cold.",
    "The train arrived late, as expected, but no one complained. Travelers stood patiently, scrolling through phones or staring into space. When the doors finally opened, the platform came alive with movement.",
    "Compiling the source code took longer than expected, but the final binary was surprisingly small. Optimization is an art that requires patience and a deep understanding of memory management and CPU cycles.",
    "He tried to focus on the screen, but his thoughts kept drifting away. Every notification felt louder than the last. Eventually, he shut everything down and sat in silence, realizing how rare that moment was.",
    "He checked his watch for the fifth time in a minute. The meeting was supposed to start at noon, but the hallway remained eerily empty. Perhaps he had the wrong day, or perhaps everyone else knew something he didn't.",
    "Virtual reality offers a glimpse into worlds that exist only in code. Pixels transform into mountains, and algorithms simulate the feeling of gravity, blurring the line between what is tangible and what is merely imagined.",
    "A gentle breeze carried the scent of blooming flowers across the peaceful countryside while birds sang cheerful melodies, children laughed in the distance, and the golden sunlight painted every field with remarkable beauty.",
    "The morning air felt unusually quiet as the city slowly woke up. A single bicycle passed by, its wheels humming softly against the road. Somewhere nearby, a shopkeeper lifted a shutter and sighed, ready for another long day.",
    "She found an old notebook hidden behind the bookshelf. The pages were filled with half-written ideas and strange sketches that made no sense at first. After a while, patterns began to emerge, and curiosity replaced confusion.",
    "Rain started falling without warning, tapping rapidly on the windows. People rushed for shelter while the streets turned reflective and slick. The storm passed as quickly as it arrived, leaving behind the smell of wet earth.",
    "A leaf floated onto the page just as she began to write, and its thin veins caught the light while the autumn breeze turned the corner. It reminded her that the garden was changing even as she tried to hold the moment in words.",
    "Her tea cooled beside the lamp while she continued reading, and the room grew softer around her as the light made warm shadows on the wall. The page turned slowly, and the night outside settled against the window like a quiet companion.",
    "Her keys rested beside the bowl, exactly where she had left them the night before, and the small relief of finding them made the morning feel less rushed. For a moment, it seemed as though the house had decided to help her leave on time.",
    "A bus pulled to a stop, its brakes releasing a soft hiss as the doors folded open, and a few passengers stepped out into the cool evening air. Others waited near the curb, holding umbrellas and checking the route number before climbing aboard.",
    "He locked the door twice, then paused on the step to listen for any sound from inside before walking toward the car. Habit had taught him that a few extra seconds of checking could prevent a long day of worry, even if everything was probably fine.",
    "The stairs groaned underfoot, each step announcing the journey upward through the quiet house, and by the time the landing was reached, the sound had become part of the evening. It blended with the clock in the hall and the wind against the window.",
    "The compass needle trembled before settling toward the north, and the traveler watched it closely, aware that a single uncertain direction could turn the path into a longer route through unfamiliar hills. The forest around them seemed to wait for the decision.",
    "The chessboard waited quietly on the table, its pieces arranged with careful precision, while the late afternoon sun crossed the squares. Every move had already been discussed in their minds, and the silence felt heavier than the clock ticking beside the board.",
    "The answer was simpler than expected, and once it was written on the board, the room grew quiet while everyone retraced the steps. It was strange how a complicated problem could hide such a straightforward solution, waiting for someone to ask the right question.",
    "She tied her shoes quickly, checked the time on the wall clock, and stepped outside before the first drops of rain could reach the porch. Being early might make the difference between a calm morning and a hurried one, and she was not in the mood to be late again.",
    "The soup needed more salt, so she added a careful pinch, stirred it slowly, and tasted it again while the pot simmered on the stove. The kitchen filled with the warm smell of herbs, onions, and fresh bread, making the small meal feel like a comfort after a long day.",
    "Morning light touched the table, moving slowly across the cups, the folded newspaper, and the edge of an envelope that had not been opened yet. The room was still quiet, and the light seemed to wait, as if the day were gently asking whether anyone was ready to begin.",
    "A red scarf hung on the hook beside the door, still damp from the morning walk, and every time someone passed it, they remembered the cold wind, the bright leaves, and the sudden decision to stay outside a little longer. It added a small spot of color to the otherwise quiet hallway.",
    "The elevator stopped on every floor, giving people time to glance at the doors, adjust their bags, and listen to the soft hum of the cables. By the time it reached the top, the ride had become less like a simple trip upward and more like a strange pause between one task and the next.",
    "Wind moved through the wheat, bending the stems in long silver waves, and the farmer stood at the fence for a moment, watching the field shift under the clouds. It felt as though the whole season were breathing quietly before harvest, and the air carried the dry scent of ripening grain.",
    "The kettle clicked off, and the sudden silence made the kitchen feel larger, while steam rose from the spout and curled toward the window where a thin line of morning light was beginning to spread across the table. Someone reached for a cup, and the day started with a small, familiar ritual.",
    "The printer jammed again, and the office fell into the familiar routine of opening panels, removing paper with careful hands, and restarting the machine while someone joked about its terrible timing. When the green light finally returned, everyone went back to work as if nothing unusual had happened.",
    "The puzzle had taken most of the afternoon, and the picture was almost complete except for one missing piece that seemed to have vanished into the carpet, under the chair, or somewhere behind the shelf. Everyone searched slowly, moving books and cushions, because finishing it had become a matter of quiet pride.",
    "Snow melted along the edges of the road, turning the gravel dark and sending small streams toward the drain, while the morning air felt cleaner and the rooftops began to drip in a slow, steady rhythm. It promised warmer weather, and the street sounded different, softer somehow, as if winter were slowly letting go.",
    "The city market closed slowly as vendors folded their canopies and packed unsold fruit into wooden crates. The last bus arrived with a hiss of brakes, and a few tired passengers stepped into the square while pigeons scattered across the wet stones. Above the rooftops, the sky turned from gray to a deep evening blue.",
    "The notebook fell open to a sketch drawn in quick pencil lines, and although the artist had forgotten making it, the image brought back the sound of rain on the window, the smell of ink, and the feeling of waiting for an idea to become clear. For a moment, the page seemed more important than the blank sheets that followed.",
    "The experiment required exactly 4.5 liters of solution, heated to 75 degrees Celsius. If the temperature dropped by even 2%, the entire reaction would fail, costing the team months of hard work and nearly $50,000 in lost materials. Precision wasn't just a goal; it was the only way to survive the rigorous demands of the laboratory environment.",
    "The workshop smelled of sawdust and oil, and tools hung in careful rows along the wall. A carpenter measured each board twice, cut slowly, and sanded the edges until they were smooth. The finished chair sat near the window, waiting for a final coat of varnish before it could be delivered to the customer. It was simple work, but it required patience and attention.",
    "The lighthouse stood alone on the cliff, sending its beam across the dark water every few seconds. Below, waves struck the rocks and broke into white foam. The keeper climbed the narrow stairs, checked the lamp, and wrote a short note in the logbook, knowing that distant ships depended on that steady light. Before dawn, fog rolled in and made the horn sound again.",
    "The desert cooled quickly after sunset, and the sand turned from gold to silver under the rising moon. A small camp sat near the rocks, its fire sending sparks into the still air. The travelers shared bread, checked their maps, and spoke in low voices about the long journey that still waited beyond the dunes. Somewhere far away, a coyote cried once and then silence returned.",
    "The observatory sat on a high plateau where the night sky seemed unusually clear. Astronomers checked their instruments, compared old charts, and waited for the clouds to move away. When the telescope finally pointed toward a faint comet, the room filled with quiet excitement and the soft tapping of keyboards. It was the kind of moment that reminded them why they loved science.",
    "The research team gathered around the monitor as the final numbers appeared on the screen. After weeks of testing, the results were clearer than anyone had expected, and a relieved silence spread through the room. Someone laughed quietly, someone saved the file, and the project leader began writing the summary for the next morning. It was not the end of the work, but it was an important step forward.",
    "The old railway station had a high ceiling, tall windows, and a clock that never seemed to hurry. Travelers sat on wooden benches with suitcases at their feet, while announcements echoed softly overhead. Outside, the morning fog rested over the tracks, turning the signals into faint red and green shapes in the distance. A vendor pushed a small cart along the platform and called out coffee and pastries.",
    "Waves crashed against the jagged rocks, sending salty spray high into the air. The ocean was restless today, churning with a deep green intensity that signaled a coming storm. Far out on the horizon, a single ship struggled against the rising tide, its mast swaying dangerously. It was a stark reminder of how small we really are compared to the vast, untamed power of the natural world, yet we keep sailing forward anyway.",
    "Deep in the forest, the ancient trees whispered secrets to the wind. Every rustle of a leaf felt like a syllable in a language forgotten by humans long ago. Explorers often came here seeking answers, but most left with only more questions and a strange sense of longing for a home they had never actually visited. It was a place where time didn't follow the usual rules, and the stars seemed much closer than they did in the crowded cities.",
];

pub fn get_random_text() -> &'static str {
    let index = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap()
        .as_secs() as usize
        % RANDOM_TEXTS.len();
    RANDOM_TEXTS[index]
}
