# Build stage
FROM rust:1.94 AS builder
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src

# Build in release mode
RUN cargo build --release

# Runtime stage
FROM debian:bookworm-slim
WORKDIR /app

# Copy the compiled binary
COPY --from=builder /app/target/release/server .

EXPOSE 8000

# Run the application
CMD ["./server"]